import tornado.web
import tornado.httpserver
import tornado.ioloop
import tornado.options
from uuid import uuid4

class ShoppingCart(object):
	totalInventory = 10
	callbacks = []
	carts = {} # list of shoppers who have added to their carts
	
	def register(self, callback):
		self.callbacks.append(callback)
	
	def moveItemToCart(self, session):
		if session in self.carts:
			return
		
		self.carts[session] = True
		self.notifyCallbacks()
	
	def removeItemFromCart(self, session):
		if session not in self.carts:
			return
		
		del(self.carts[session])
		self.notifyCallbacks()
	
	def notifyCallbacks(self):
		self.callbacks[:] = [c for c in self.callbacks if self.callbackHelper(c)]
	
	def callbackHelper(self, callback):
		callback(self.getInventoryCount())
		return False
	
	def getInventoryCount(self):
		return self.totalInventory - len(self.carts)

class DetailHandler(tornado.web.RequestHandler):
	# to render the HTML
	# this generates a unique id for each request, gets the inventory count
	# and renders that into a HTML page
	def get(self):
		session = uuid4()
		count = self.application.shoppingCart.getInventoryCount()
		self.render("index.html", session=session, count=count)

class CartHandler(tornado.web.RequestHandler):
	# an interface to manipulate the cart
	# This provides an API for broswer to add or remove the item from cart.
	# the js running in browser will send POST requests. and this
	# CartHandler function handles them 
	def post(self):
		action = self.get_argument('action')
		session = self.get_argument('session')
		
		# session is a uuid generated by Detail Handler. If there is no 
		# session key in POST request, then it is invalid. Set status to 400
		if not session:
			self.set_status(400)
			return
		
		# if action is add the item to cart, add the session key (uuid) to
		# cart 
		if action == 'add':
			self.application.shoppingCart.moveItemToCart(session)
		elif action == 'remove':
			self.application.shoppingCart.removeItemFromCart(session)
		else:
			self.set_status(400)

class StatusHandler(tornado.web.RequestHandler):
	# this probably maintains the cart status
	# this keeps the connection open with the browser
	# whenever there is change in inventory number, this pushes to client
	@tornado.web.asynchronous
	def get(self):
		# Here we register a callback with the shopping cart controller. 
		# We wrap the callback method with self.async_callback to ensure that 
		# exceptions raised in the callback don’t prevent the
		# RequestHandler from properly closing the connection.
		self.application.shoppingCart.register(self.async_callback(self.on_message))
	
	def on_message(self, count):
		self.write('{"inventoryCount":"%d"}' % count)
		self.finish()
		
class Application(tornado.web.Application):
	def __init__(self):
		self.shoppingCart = ShoppingCart()
		
		handlers = [
			(r'/', DetailHandler),
			(r'/cart', CartHandler),
			(r'/cart/status', StatusHandler)
		]
		
		settings = {
			'template_path': 'templates',
			'static_path': 'static'
		}
		
		tornado.web.Application.__init__(self, handlers, **settings)

if __name__ == '__main__':
	tornado.options.parse_command_line()
	
	app = Application()
	server = tornado.httpserver.HTTPServer(app)
	server.listen(8000)
	tornado.ioloop.IOLoop.instance().start()
